apiVersion: apps/v1
kind: Deployment
metadata:
  name: cephtools
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: cephtools
      volumes:
      - name: external-cluster-details
        secret:
          secretName: rook-ceph-external-cluster-details
      - name: workspace
        emptyDir: {}
      - name: scripts
        configMap:
          name: cephtools-scripts

      containers:
      - name: cephtools
        workingDir: /etc/ceph
        image: registry.redhat.io/odf4/cephcsi-rhel9:v4.17
        volumeMounts:
        - name: external-cluster-details
          mountPath: /ceph
        - name: workspace
          mountPath: /etc/ceph
        - name: scripts
          mountPath: /scripts
        command:
        - bash
        - -c
        - |
            python3 /scripts/generate-ceph-config.py
            sleep inf
