apiVersion: apps/v1
kind: Deployment
metadata:
  name: cephtools
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: cephtools
      volumes:
      - name: external-cluster-details
        secret:
          secretName: rook-ceph-external-cluster-details
      - name: workspace
        emptyDir: {}

      containers:
      - name: cephtools
        workingDir: /etc/ceph
        image: ghcr.io/larsks/cephtools:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: external-cluster-details
          mountPath: /ceph
        - name: workspace
          mountPath: /etc/ceph
        command:
        - bash
        - -c
        - |
            python3 /scripts/generate-ceph-config.py
            sleep inf
