apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cephtools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cephtools
subjects:
- kind: ServiceAccount
  name: cephtools
  namespace: openshift-storage
