apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cephtools
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
