apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../cephtools
- clusterrolebinding.yaml

patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cephtools
      spec:
        template:
          spec:
            containers:
            - name: cephtools
              securityContext:
                privileged: true
